Updated run_and_test.yml
updated the file to include score evaluation.

diff --git a/.github/workflows/run_and_test.yml b/.github/workflows/run_and_test.yml
--- a/.github/workflows/run_and_test.yml
+++ b/.github/workflows/run_and_test.yml
@@ -21,5 +21,13 @@ jobs:
       - name: Pull Docker image from registry
         run: docker pull sambandh/CICD_Assignment:v1
 
-      - name: Run Docker container
-        run: docker run sambandh/CICD_Assignment:v1
+      - name: Run and Test Docker container
+        run: |
+          OUTPUT=$(docker run sambandh/CICD_Assignment:v1)
+          echo "Score = $OUTPUT"
+          if [[ $(echo "$OUTPUT 0.50" | awk '{print ($1 < $2)}') == 1 ]]; then
+            echo "FAILED : Score is less than 0.50"
+            exit 1
+          else
+            echo "PASSED : Score is greater than 0.50"
+          fi        
