modified dockerfile and actions

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -1,18 +1,31 @@
-name: test
+
+name: Pull and Run Docker Image
+
 on:
-  pull_request:
-    branches: [ main ]
+  workflow_run:
+    workflows: ["Build and Push Docker Image"]
+    branches: [main]
+    types:
+      - completed
 
 jobs:
-  run-tests:
+  pull-and-run:
     runs-on: ubuntu-latest
-    needs: build-and-push
-
     steps:
-    - uses: actions/checkout@v3
-
-    - name: Pull Docker Image
-      run:  docker pull ashivamdocker/CICD_Assignment:latest
-
-    - name: Run tests in Docker container
-      run:  docker run --rm ashivamdocker/CICDAssignment:latest
+    - name: Login to Docker Hub
+      uses: docker/login-action@v1
+      with:
+        username: ${{ secrets.DOCKER_USERNAME }}
+        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
+    - name: Pull the Docker image
+      run: docker pull ashivamdocker/ci_cd_docker:latest
+    - name: Run the Docker image
+      run: docker run --name test_container ashivamdocker/ci_cd_docker:latest
+    - name: Check test results
+      run: |
+        if docker logs test_container | grep -q 'Score: 0.5'; then
+          echo "Test passed with a score above 0.5"
+        else
+          echo "Test failed with a score below 0.5"
+          exit 1
+        fi
